### ISSUE TITLE
As a user I want to be able to log in as an instructor to teach others.

### ISSUE THREAD

**Issue by kzikaras** [kzikaras/bloc-capstone#7]
Allow users to sign in as an instructor
![Imgur](https://i.imgur.com/f5O9SuM.jpg)

**Comment by johnksawers** [comment]
I would suggest splitting this into two tasks. One for each type. Also think about if Instructors will ever want to get support as a user from other Instructors. Allowing this adds a lot of complexity, so it's completely reasonable to punt on a feature like this until you're sure it's worth the time.
