### ISSUE TITLE
As an instructor I would like to see a dashboard with a summary of my account and any feedback from users I have helped.

### ISSUE THREAD

**Issue by kzikaras** [kzikaras/bloc-capstone#8]
Create a dashboard for instructors.
![Imgur](https://i.imgur.com/D0py73E.jpg)

**Comment by johnksawers** [comment]
I would suggest rephrasing this in a standard user story format:

"As an instructor I want one place the shows me..." the '...' part is all the things the instructor wants to see on the dashboard.
The key is getting into the user's frame of mind.
